sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.spark_nlp.dep.cache

jobs:
  include:
    - stage: build
    - script: docker build -t spark-nlp-scala -f .ci/Dockerfile .
    - stage: scala
    - script: docker run spark-nlp-scala sbt test 
    - stage: python
    - script: docker build -t spark-nlp-python-2 -f .ci/DockerfilePy2 .
    - stage: docker run spark-nlp-python-2 python2 run-tests.py
    - script: docker build -t spark-nlp-python-3 -f .ci/DockerfilePy3 .
    - stage: docker run spark-nlp-python-3 python3 run-tests.py
