cache:
  directories:
    - $HOME/.spark_nlp.dep.cache

sbt_args: -J-Xmx6G -J-XX:+UseConcMarkSweepGC -J-XX:+CMSClassUnloadingEnabled -J-XX:MaxPermSize=6G -J-Xms2G -J-Xss64M -J-XX:+AggressiveOpts

matrix:
  include:
    - language: python
      python: 2.7
      before_script:
        - sbt assemblyAndCopy
        - pip install pyspark
        - pip install numpy
        - cd python/
      script:
        - python run-tests.py

    - language: python
      python: 3.6
      before_script:
        - sbt assemblyAndCopy
        - pip install pyspark
        - pip install numpy
        - cd python/
      script:
        - python run-tests.py

    - language: scala
      scala: 2.11.11
      before_script:
        - _JAVA_OPTIONS="-Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=6G -Xms2G -Xss64M -XX:+AggressiveOpts"
      script:
        - sbt clean coverage test coverageReport
      after_success:
        - bash <(curl -s https://codecov.io/bash)
