cache:
  directories:
    - $HOME/.spark_nlp.dep.cache

matrix:
  include:
    - language: python
      python: 2.7
      before_script:
        - sbt assemblyAndCopy
        - cd python/
      script:
        - python run-tests.py

    - language: python
      python: 3.6
      before_script:
        - sbt assemblyAndCopy
        - cd python/
      script:
        - python run-tests.py

