cache:
  directories:
    - $HOME/.spark_nlp.dep.cache

sbt_args: -J-Xmx8G -J-XX:+UseConcMarkSweepGC -J-XX:+CMSClassUnloadingEnabled -J-XX:MaxPermSize=6G -J-Xss2M

matrix:
  include:
    - language: python
      python: 2.7
      before_script:
        - sbt assemblyAndCopy
        - pip install pyspark
        - pip install numpy
        - cd python/
      script:
        - python run-tests.py

    - language: python
      python: 3.6
      before_script:
        - sbt assemblyAndCopy
        - pip install pyspark
        - pip install numpy
        - cd python/
      script:
        - python run-tests.py

    - language: scala
      scala: 2.11.11
