sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.spark_nlp.dep.cache

jobs:
  include:
    - stage: build
      install: skip
      script: 
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t "$DOCKER_USERNAME"/spark-nlp-scala -f .ci/Dockerfile .
        - docker push "$DOCKER_USERNAME"/spark-nlp-scala
    - stage: scala
      install: skip
      language: scala
      script: docker run "$DOCKER_USERNAME"/spark-nlp-scala sbt test 
    - stage: python
      install: skip
      language: python
      python: "2.7"
      script:
        - docker build --build-arg from="$DOCKER_USERNAME"/spark-nlp-scala -t spark-nlp-python-2 -f .ci/DockerfilePy2 .
        - docker run spark-nlp-python-2 python2 run-tests.py
    - language: python
      python: "3.5"
      script:
       - docker build --build-arg from="$DOCKER_USERNAME"/spark-nlp-scala -t spark-nlp-python-3 -f .ci/DockerfilePy3 .
       - docker run spark-nlp-python-3 python3 run-tests.py
