sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.spark_nlp.dep.cache

jobs:
  include:
    - stage: build
      script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      script: docker build -t "$DOCKER_USERNAME"/spark-nlp-scala -f .ci/Dockerfile .
      script: docker push "$DOCKER_USERNAME"/spark-nlp-scala
    - stage: scala
      script: docker run "$DOCKER_USERNAME"/spark-nlp-scala sbt test 
    - stage: python2
      script: docker build --build-arg from="$DOCKER_USERNAME"/spark-nlp-scala -t spark-nlp-python-2 -f .ci/DockerfilePy2 .
      script: docker run spark-nlp-python-2 python2 run-tests.py
    - stage: python3
      script: docker build --build-arg from="$DOCKER_USERNAME"/spark-nlp-scala -t spark-nlp-python-3 -f .ci/DockerfilePy3 .
      script: docker run spark-nlp-python-3 python3 run-tests.py
